### ISSUE TITLE
customize max-width of screens and correct responsiveness

### ISSUE THREAD

**Issue by sasha-astiadi** [ourworld-tsc/www_ourphone#1]
we need to figure out the correct max width values for different screens, small to big

![2023-01-05 00 44 57](https://user-images.githubusercontent.com/43240801/210606033-c2eb5365-6332-41bc-bd47-4434fb5d3759.jpg)

Kristof KDS, [5. Jan 2023 at 00:21:15]:
...he max widht needs to be limited of a page

so if we scale out more it gets free spaces at both sides

can someone help me fix it? e.g.for this website ourphone.

if we find solutions please explain here what to do, so i can try on my own, for our other website,, thank you

**Comment by ehab-hassan** [comment]
@despiegk @sasha-astiadi 
to fix this we need to add container ( I added at md
check it please if it works with u
https://ourphone.ourworld.tf/
